<!DOCTYPE html>
<html>
<head>
    <title>Online chat Web-fomin.ru | Slim, php, socket, vkAuth</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="<?= $basePath ?>/css/chat.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script type="text/javascript">
        var cookie = "";
        //console.log(cookie);
        var sessionMessage = {
            "PHPSESSID" : cookie
        };
        var socket = new WebSocket("ws://192.168.56.101:8000/<?php echo $_COOKIE['PHPSESSID'] ?>");
        socket.onopen = function() {
            alert("Соединение установлено.");
            socket.send(JSON.stringify(sessionMessage));
        };

        socket.onclose = function(event) {
            if (event.wasClean) {
                alert('Соединение закрыто чисто');
            } else {
                alert('Обрыв соединения'); // например, "убит" процесс сервера
            }
            alert('Код: ' + event.code + ' причина: ' + event.reason);
        };

        socket.onmessage = function(event) {
            //alert("Получены данные " + event.data);
            console.log('Получены данные ' + event.data);
        };

        socket.onerror = function(error) {
            alert("Ошибка " + error.message);
        };
    </script>
    <script src="<?= $basePath ?>/js/client.js"></script>

</head>
<body>
<div class="container">

</div>
<div class="control">
    <form>
        <input type="text" name="text" id="text" placeholder="Type message and press Enter" tabindex="1">
    </form>
</div>
</body>
</html>